# specify which database and adapter to use for which environment
#view using psql <table name below> and \dt to view the table

development:
  adapter: postgresql
  database: rush-hour-development

test:
  adapter: postgresql
  database: rush-hour-test

production:
  adapter: postgresql
  database: rush-hour-production
