# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: traffic-spy-development
  host: localhost

test:
  adapter: postgresql
  database: traffic-spy-test

production:
  adapter: postgresql
  database: traffic-spy-production
